version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: crediexpress_postgres
    environment:
      POSTGRES_USER: IN6AM
      POSTGRES_PASSWORD: In6amKnl!
      POSTGRES_DB: crediexpress
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - crediexpress_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U IN6AM"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: crediexpress_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: In6amKnl!
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - crediexpress_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongodb_data:

networks:
  crediexpress_network:
    driver: bridge 